from .enum_util import AutoLowerNameEnum
from enums import auto, unique


@unique
class Enchantments(AutoLowerNameEnum):
    AQUA_AFFINITY = auto()
    BANE_OF_ARTHROPODS = auto()
    BINDING_CURSE = auto()
    BLAST_PROTECTION = auto()
    CHANNELING = auto()
    DEPTH_STRIDER = auto()
    EFFICIENCY = auto()
    FEATHER_FALLING = auto()
    FIRE_ASPECT = auto()
    FIRE_PROTECTION = auto()
    FLAME = auto()
    FORTUNE = auto()
    FROST_WALKER = auto()
    IMPALING = auto()
    INFINITY = auto()
    KNOCKBACK = auto()
    LOOTING = auto()
    LOYALTY = auto()
    LUCK_OF_THE_SEA = auto()
    LURE = auto()
    MENDING = auto()
    MULTISHOT = auto()
    PIERCING = auto()
    POWER = auto()
    PROJECTILE_PROTECTION = auto()
    PROTECTION = auto()
    PUNCH = auto()
    QUICK_CHARGE = auto()
    RESPIRATION = auto()
    RIPTIDE = auto()
    SHARPNESS = auto()
    SILK_TOUCH = auto()
    SMITE = auto()
    SWEEPING = auto()
    THORNS = auto()
    UNBREAKING = auto()
    VANISHING_CURSE = auto()
